import jsPDF from 'jspdf';

export function generatePDF(entries, schema, programName) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;
  const dateStr = new Date().toISOString().split('T')[0];

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`EXPORT LIST — ${programName || 'Untitled'} — ${dateStr}`, margin, y);
  y += 10;
  doc.setDrawColor(180);
  doc.line(margin, y, margin + contentWidth, y);
  y += 8;

  for (const entry of entries) {
    if (y > 270) { doc.addPage(); y = margin; }
    doc.setFillColor(28, 28, 34);
    doc.roundedRect(margin, y, contentWidth, 18, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(59, 130, 246);
    doc.text(entry.id, margin + 4, y + 6);
    doc.setFontSize(9);
    doc.setFont('courier', 'bold');
    doc.setTextColor(232, 232, 236);
    doc.text(entry.filename, margin + 16, y + 6, { maxWidth: contentWidth - 20 });
    if (entry.metadata?.description) {
      doc.setFontSize(8);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(136, 136, 160);
      doc.text(entry.metadata.description, margin + 16, y + 13, { maxWidth: contentWidth - 20 });
    }
    y += 22;
  }

  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(136, 136, 160);
    doc.text(`Generated by Nomenklatura — ${dateStr} — Page ${i}/${pageCount}`, pageWidth / 2, 290, { align: 'center' });
  }

  doc.save(`${programName || 'export'}_${dateStr}.pdf`);
}
