import jsPDF from 'jspdf';

const SEGMENT_COLORS = {
  program:     [96, 165, 250],
  version:     [167, 139, 250],
  language:    [52, 211, 153],
  fileformat:  [251, 146, 60],
  videoformat: [34, 211, 238],
  videoaspect: [244, 114, 182],
  videores:    [129, 140, 248],
  cadence:     [212, 165, 116],
  audioformat: [248, 113, 113],
  audiocodec:  [148, 163, 184],
  date:        [125, 211, 252],
};

const SEPARATOR_COLOR = [100, 100, 120];
const BG_DARK = [18, 18, 22];
const BG_CARD = [28, 28, 36];
const TEXT_MUTED = [120, 120, 145];
const TEXT_PRIMARY = [232, 232, 236];
const ACCENT = [59, 130, 246];
const GOLD = [193, 171, 123];

function svgToImage(svgUrl) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      const scale = 2;
      canvas.width = img.width * scale;
      canvas.height = img.height * scale;
      const ctx = canvas.getContext('2d');
      ctx.scale(scale, scale);
      ctx.drawImage(img, 0, 0, img.width, img.height);
      resolve(canvas.toDataURL('image/png'));
    };
    img.onerror = reject;
    img.crossOrigin = 'anonymous';
    img.src = svgUrl;
  });
}

function drawColoredSegments(doc, segments, x, y, fontSize, maxWidth) {
  doc.setFontSize(fontSize);
  doc.setFont('courier', 'bold');
  let curX = x;

  for (let i = 0; i < segments.length; i++) {
    if (i > 0) {
      doc.setTextColor(...SEPARATOR_COLOR);
      doc.text('_', curX, y);
      curX += doc.getTextWidth('_');
    }

    const seg = segments[i];
    const color = SEGMENT_COLORS[seg.type] || TEXT_PRIMARY;
    doc.setTextColor(...color);

    const text = seg.value;
    const available = maxWidth - (curX - x);
    if (doc.getTextWidth(text) > available && available > 0) {
      let truncated = text;
      while (doc.getTextWidth(truncated + '…') > available && truncated.length > 1) {
        truncated = truncated.slice(0, -1);
      }
      doc.text(truncated + '…', curX, y);
      curX += doc.getTextWidth(truncated + '…');
      break;
    } else {
      doc.text(text, curX, y);
      curX += doc.getTextWidth(text);
    }
  }
}

export async function generatePDF(entries, schema, programName) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  const dateStr = new Date().toISOString().split('T')[0];

  let logoData = null;
  try {
    const baseUrl = import.meta.env.BASE_URL || '/';
    logoData = await svgToImage(`${baseUrl}SB_NOBG_BLACK.svg`);
  } catch {
    // logo loading failed, continue without it
  }

  function drawPageBackground() {
    doc.setFillColor(...BG_DARK);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
  }

  function drawHeader(y) {
    if (logoData) {
      const logoH = 8;
      const logoW = logoH * (960 / 268);
      doc.addImage(logoData, 'PNG', margin, y - 3, logoW, logoH);
    }

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...TEXT_PRIMARY);
    const titleY = y + 14;
    doc.text('EXPORT LIST', margin, titleY);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...GOLD);
    doc.text(`${programName || 'Untitled'}`, margin, titleY + 6);

    doc.setTextColor(...TEXT_MUTED);
    doc.setFontSize(8);
    doc.text(dateStr, margin + contentWidth, titleY + 6, { align: 'right' });

    const lineY = titleY + 10;
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.3);
    doc.line(margin, lineY, margin + contentWidth, lineY);

    return lineY + 6;
  }

  function drawFooter(pageNum, totalPages) {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...TEXT_MUTED);
    doc.text(
      `Generated by Nomenklatura — ${dateStr}`,
      margin, pageHeight - 8
    );
    doc.text(
      `${pageNum} / ${totalPages}`,
      pageWidth - margin, pageHeight - 8,
      { align: 'right' }
    );
  }

  drawPageBackground();
  let y = drawHeader(margin);

  const entryHeight = 16;
  const entryGap = 3;

  for (let idx = 0; idx < entries.length; idx++) {
    const entry = entries[idx];
    const hasDesc = !!entry.metadata?.description;
    const cardH = hasDesc ? entryHeight + 5 : entryHeight;

    if (y + cardH > pageHeight - 18) {
      doc.addPage();
      drawPageBackground();
      y = margin + 6;
    }

    doc.setFillColor(...BG_CARD);
    doc.roundedRect(margin, y, contentWidth, cardH, 1.5, 1.5, 'F');

    doc.setFillColor(...ACCENT);
    doc.roundedRect(margin + 3, y + 3, 10, 6, 1, 1, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text(entry.id, margin + 8, y + 7.2, { align: 'center' });

    drawColoredSegments(doc, entry.segments, margin + 16, y + 7, 8, contentWidth - 20);

    if (hasDesc) {
      doc.setFontSize(7);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...TEXT_MUTED);
      doc.text(entry.metadata.description, margin + 16, y + 13, { maxWidth: contentWidth - 20 });
    }

    y += cardH + entryGap;
  }

  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(i, totalPages);
  }

  doc.save(`${programName || 'export'}_${dateStr}.pdf`);
}
